[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "webapp-photo-luminescence"
description = "A web application for photo luminescence measurement"
readme = "README.md"
requires-python = "~=3.10"
license = "MIT"
authors = [
  { name = "Shuhei Nitta", email = "huisintheta@gmail.com" }
]
keywords = []
classifiers = []
dependencies = [
  "dash~=2.6.1",
  "dash-bootstrap-components~=1.2.1",
  "pandas~=1.4.4",
  "tlab-analysis{'git': 'https://github.com/wasedatakeuchilab/tlab-analysis', 'rev': 'v0.0.2'}",
  "tlab-pptx{'git': 'https://github.com/wasedatakeuchilab/tlab-pptx', 'rev': 'v0.0.2'}",
]
dynamic = ["version"]

[project.urls]
Documentation = ""
Homepage = "https://github.com/wasedatakeuchilab/webapp-photo-luminescence"

[project.optional-dependencies]
test = []
dev = []
doc = []

[tool.hatch.version]
path = "src/webapp_photo_luminescence/__init__.py"

[tool.mypy]
python_version = "3.10"
strict = true

[[tool.mypy.overrides]]
module = [
  "dash.*",
  "dash_bootstrap_components.*",
  "plotly.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=webapp_photo_luminescence"
testpaths = ["tests"]
