[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dawa-trpl"
description = "A web application for TRPL measurement"
readme = "README.md"
requires-python = "~=3.10"
license = "MIT"
authors = [
  { name = "Shuhei Nitta", email = "huisintheta@gmail.com" }
]
# keywords = []
# classifiers = []
dependencies = [
  "dash~=2.11.1",
  "dash-bootstrap-components~=1.4.1",
  "pandas~=2.0.2",
  "tlab-analysis @ git+https://github.com/wasedatakeuchilab/tlab-analysis@v0.2.3",
  "tlab-pptx @ git+https://github.com/wasedatakeuchilab/tlab-pptx@v0.1.3",
  "asgiref~=3.7.1",
]
dynamic = ["version"]

[project.urls]
Documentation = ""
Homepage = "https://github.com/wasedatakeuchilab/dawa-trpl"

[project.optional-dependencies]
test = [
  "pytest==7.4.0",
  "pytest-cov==4.1.0",
  "pytest-describe==2.1.0",
  "pytest-mock==3.11.1",
  "mypy==1.5.1",
  "flake8==6.1.0",
  "isort==5.12.0",
  "black==23.7.0",
]
stub = [
  "pandas-stubs~=2.0.2",
]
doc = []

[tool.hatch.version]
path = "src/dawa_trpl/__init__.py"

[tool.hatch.envs.test]
features = ["test", "stub"]

[tool.hatch.envs.test.scripts]
test = "scripts/test.sh {args}"
format = "scripts/format.sh {args}"
lint = "scripts/lint.sh {args}"

[tool.hatch.envs.doc]
features = ["doc"]

[tool.hatch.envs.doc.scripts]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
strict = true
sqlite_cache = true
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = [
  "dash.*",
  "dash_bootstrap_components.*",
  "plotly.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=dawa_trpl"

[tool.coverage.run]
omit = ["*/__main__.py"]
