[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dawa-trpl"
description = "A web application for TRPL measurement"
readme = "README.md"
requires-python = "~=3.10"
license = "MIT"
authors = [
  { name = "Shuhei Nitta", email = "huisintheta@gmail.com" }
]
keywords = []
classifiers = []
dependencies = [
  "dash~=2.6.1",
  "dash-bootstrap-components~=1.2.1",
  "pandas~=1.5.1",
  "tlab-analysis @ git+https://github.com/wasedatakeuchilab/tlab-analysis@v0.1.1",
  "tlab-pptx @ git+https://github.com/wasedatakeuchilab/tlab-pptx@v0.1.1",
  "asgiref~=3.5.2",
]
dynamic = ["version"]

[project.urls]
Documentation = ""
Homepage = "https://github.com/wasedatakeuchilab/dawa-trpl"

[project.optional-dependencies]
test = [
  "pytest~=7.2.0",
  "pytest-cov~=4.0.0",
  "pytest-describe~=2.0.1",
  "mypy~=0.971",
  "flake8~=5.0.4",
  "isort~=5.10.1",
  "black~=22.10.0",
  "pandas-stubs~=1.5.1",
]
dev = [
  "pre-commit~=3.0.0",
  "uvicorn~=0.19.0",
]
doc = []
prod = [
  "uvicorn~=0.19.0",
]

[tool.hatch.version]
path = "src/dawa_trpl/__init__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
python_version = "3.10"
strict = true
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = [
  "dash.*",
  "dash_bootstrap_components.*",
  "plotly.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=dawa_trpl"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["*/__main__.py"]
