[tool.poetry]
name = "webapp-photo-luminescence"
version = "0.0.0"  # dummy version. The actual version is __version__ in __init__.py
description = "A web application for photo luminescence measurement"
license = "MIT"
authors = ["Shuhei Nitta <huisintheta@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/wasedatakeuchilab/webapp-photo-luminescence"
repository = "https://github.com/wasedatakeuchilab/webapp-photo-luminescence"

[tool.poetry.dependencies]
python = "~3.10"
dash = "^2.6.1"
dash-bootstrap-components = "^1.2.1"
pandas = "^1.5.0"
tlab-analysis = {git = "https://github.com/wasedatakeuchilab/tlab-analysis", rev = "v0.0.2"}
tlab-pptx = {git = "https://github.com/wasedatakeuchilab/tlab-pptx", rev = "v0.0.2"}

[tool.poetry.dev-dependencies]
mypy = "^0.971"
flake8 = "^5.0.4"
isort = "^5.10.1"
black = "^22.8.0"
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
pytest-describe = "^2.0.1"
pandas-stubs = "^1.4.4.220912"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
folders = [
  { path = "src" }
]

[tool.mypy]
python_version = "3.10"
strict = true
disallow_untyped_decorators = false


[[tool.mypy.overrides]]
module = [
  "dash.*",
  "dash_bootstrap_components.*",
  "plotly.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.black]
target-version = ["py310"]

[tool.pytest.ini_options]
addopts = "--cov=webapp_photo_luminescence --cov-report=term-missing:skip-covered"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["*/__main__.py"]
